/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#ffdadb',
        'error-container': '#93000a',
        'surface-variant': '#343537',
        'on-background': '#e3e2e4',
        'surface-container-high': '#292a2c',
        'tertiary-fixed': '#6ffbbe',
        'on-secondary': '#003640',
        'on-secondary-container': '#00424e',
        'surface-container': '#1f2022',
        'on-surface': '#e3e2e4',
        'on-primary-fixed-variant': '#92002a',
        'inverse-surface': '#e3e2e4',
        'on-error': '#690005',
        'on-primary-fixed': '#40000d',
        'secondary': '#4cd7f6',
        'surface-dim': '#121315',
        'surface': '#121315',
        'surface-container-highest': '#343537',
        'on-surface-variant': '#e3bdbf',
        'on-tertiary-fixed-variant': '#005236',
        'on-tertiary-container': '#00311f',
        'on-secondary-fixed-variant': '#004e5c',
        'surface-container-low': '#1b1c1e',
        'secondary-container': '#03b5d3',
        'on-tertiary': '#003824',
        'tertiary-fixed-dim': '#4edea3',
        'tertiary': '#4edea3',
        'outline-variant': '#5b4041',
        'on-error-container': '#ffdad6',
        'inverse-on-surface': '#303032',
        'surface-tint': '#ffb2b7',
        'surface-container-lowest': '#0d0e10',
        'error': '#ffb4ab',
        'on-secondary-fixed': '#001f26',
        'primary-fixed-dim': '#ffb2b7',
        'secondary-fixed': '#acedff',
        'surface-bright': '#38393b',
        'inverse-primary': '#bc0b3b',
        'outline': '#aa888a',
        'secondary-fixed-dim': '#4cd7f6',
        'on-primary-container': '#5b0017',
        'tertiary-container': '#00a572',
        'primary': '#ffb2b7',
        'background': '#121315',
        'primary-container': '#ff516a',
        'on-tertiary-fixed': '#002113',
        'on-primary': '#67001b',
      },
      fontFamily: {
        grotesk: ['Space Grotesk', 'sans-serif'],
        mono: ['Space Mono', 'JetBrains Mono', 'monospace'],
        sans: ['Space Grotesk', 'IBM Plex Sans', 'sans-serif'],
        'code-editor': ['Space Mono', 'JetBrains Mono', 'monospace'],
        'metric-tabular': ['Space Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
